Optimizations and a work-around for large USFM file timeouts
WycliffeAssociates/d43-catalog pull request #2
Opened 2019-09-27 19:02 UTC by rbnswartz

2020-03-19 20:34 UTC, aunger requested changes

2020-03-19 20:34 UTC, aunger commented on libraries/lambda_handlers/ts_v2_catalog_handler.py
> +        self.max_file_size = 2000000
I suggest you make this configurable instead of hardcoded. Add a environment variable on the AWS Lambda and then get it with something like this:
```python
def max_usfm_size():
  try:
    s = os.environ.get('MAX_USFM_SIZE')
    i = int(s, 10)
    return i if (i > 0) else sys.maxint
  except ValueError:
    return sys.maxint
```

2020-03-19 20:34 UTC, aunger commented on libraries/lambda_handlers/catalog_handler.py
> +        print("Checking here")
Consider using `self.logger` for consistency with the rest of the file.

2020-03-19 20:34 UTC, aunger commented on libraries/lambda_handlers/catalog_handler.py
> +        #errors = checker.check(item)
Please add a comment explaining why checking is disabled.

2020-03-19 20:34 UTC, aunger commented on libraries/lambda_handlers/catalog_handler.py
> +            #errors = checker.check_format(fmt, item)
Please add a comment explaining why checking is disabled.

2020-03-19 20:34 UTC, aunger commented on libraries/lambda_handlers/catalog_handler.py
> +                        #checker.check_format(fmt, item)
Please add a comment explaining why checking is disabled.

2020-03-19 20:34 UTC, aunger commented on libraries/lambda_handlers/ts_v2_catalog_handler.py
> +                        self.logger.debug("Skipping {} because it is too big".format(process_id))
This seems like it should be a higher log level than debug, like info or warn.

2020-03-19 20:34 UTC, aunger commented on libraries/tools/ts_v2_utils.py
> +                data = get_url('https://cdn.door43.org/bible/txt/1/{}/chunks.json'.format(pid))
Does WA keep its own list of chunks? Maybe this should be configurable.

2020-03-19 20:34 UTC, aunger commented on libraries/tools/ts_v2_utils.py
> +    return '{}'.format(num)
Nit: This function could be simplified.

2020-03-19 20:34 UTC, aunger commented on libraries/tools/ts_v2_utils.py
> +                        chapter = padded_chapter
Use your `pad_to_match` function above.

2020-03-19 20:34 UTC, aunger commented on libraries/tools/ts_v2_utils.py
> +                        verse = padded_verse
This is too complex. The `while` tests `chapter`, even though it's invariant throughout the loop.
Instead, consider using your `pad_to_match` function above.

2020-03-19 20:34 UTC, aunger commented on libraries/tools/ts_v2_utils.py
> +    print("Actual USX conversion")
Consider using the logger to match the rest of the file.

2020-07-17 14:47 UTC, PurpleGuitar approved these changes
Nothing to add beyond @aunger 's comments.  Nice work, both!

2020-07-26 03:17 UTC, aunger approved these changes
I pushed commits to address the comments.

2020-07-26 03:17 UTC, aunger commented on libraries/lambda_handlers/catalog_handler.py
> +        #errors = checker.check(item)
Done

2020-07-26 03:17 UTC, aunger commented on libraries/lambda_handlers/catalog_handler.py
> +            #errors = checker.check_format(fmt, item)
Done

2020-07-26 03:17 UTC, aunger commented on libraries/lambda_handlers/catalog_handler.py
> +                        #checker.check_format(fmt, item)
Done

2020-07-26 03:17 UTC, aunger commented on libraries/lambda_handlers/catalog_handler.py
> +        print("Checking here")
Removed

2020-07-26 03:17 UTC, aunger commented on libraries/lambda_handlers/ts_v2_catalog_handler.py
> +        self.max_file_size = 2000000
Added variable `max_usfm_size`, which defaults to your 2000000 size.

2020-07-26 03:17 UTC, aunger commented on libraries/lambda_handlers/ts_v2_catalog_handler.py
> +                        self.logger.debug("Skipping {} because it is too big".format(process_id))
Updated to `warn`

2020-07-26 03:17 UTC, aunger commented on libraries/tools/ts_v2_utils.py
> +                data = get_url('https://cdn.door43.org/bible/txt/1/{}/chunks.json'.format(pid))
Refactored. This is still an open question, but out of the scope of this PR.

2020-07-26 03:17 UTC, aunger commented on libraries/tools/ts_v2_utils.py
> +    return '{}'.format(num)
Done

2020-07-26 03:17 UTC, aunger commented on libraries/tools/ts_v2_utils.py
> +                        chapter = padded_chapter
Done (and moved up, out of this loop)

2020-07-26 03:17 UTC, aunger commented on libraries/tools/ts_v2_utils.py
> +                        verse = padded_verse
Done

2020-07-26 03:17 UTC, aunger commented on libraries/tools/ts_v2_utils.py
> +    print("Actual USX conversion")
Done

2020-07-26 03:47 UTC, merged